version: '3'
services:
  php:
    container_name: php-container
    build: ./
    ports:
      - "8080:80"
    volumes:
      - ./php-code:/var/www/html/
    links:
      - mysql:mysqldb

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "1234" 
      MYSQL_DATABASE: "simon"  
      MYSQL_USER: "admin"  
      MYSQL_PASSWORD: "1234" 
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/simon.sql  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "1234"
