version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "simon"
      MYSQL_USER: "tobi"
      MYSQL_PASSWORD: "1234"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  php:
    image: php:latest
    volumes:
      - ./php_code:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

  apache:
    image: httpd:latest
    volumes:
      - ./php_code:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    depends_on:
      - php
